/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005049",
        "surface-container-high": "#222a3d",
        "on-secondary-container": "#b0b2ff",
        "surface-dim": "#0b1326",
        "on-secondary-fixed": "#07006c",
        "secondary-container": "#3131c0",
        "surface-container-low": "#131b2e",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394d",
        "on-error": "#690005",
        "on-tertiary-container": "#4f1700",
        "secondary": "#c0c1ff",
        "tertiary-fixed": "#ffdbce",
        "on-tertiary-fixed": "#370e00",
        "surface": "#0b1326",
        "error": "#ffb4ab",
        "surface-container-lowest": "#060e20",
        "surface-tint": "#6bd8cb",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary": "#ffb59a",
        "on-primary-fixed": "#00201d",
        "on-tertiary": "#591c02",
        "primary": "#6bd8cb",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bcc9c6",
        "primary-fixed-dim": "#6bd8cb",
        "on-tertiary-fixed-variant": "#773215",
        "on-primary": "#003732",
        "error-container": "#93000a",
        "tertiary-container": "#d27956",
        "on-secondary-fixed-variant": "#2f2ebe",
        "outline": "#879391",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#3d4947",
        "secondary-fixed": "#e1e0ff",
        "primary-container": "#29a195",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#ffb59a",
        "on-secondary": "#1000a9",
        "surface-container-highest": "#2d3449",
        "on-primary-container": "#00302b",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "background": "#0b1326",
        "inverse-primary": "#006a61",
        "primary-fixed": "#89f5e7",
        
        // Legacy fallbacks for components not fully rewritten yet
        "card": "#1e293b",
        "primary-text": "#f1f5f9",
        "secondary-text": "#94a3b8",
        "border": "#3d4947",
        "cell-bg": "#1e293b",
        "chat-bubble": "#334155",
        "input-bg": "#131b2e",
        "accent": "#6bd8cb",
        "break-row-bg": "#422006",
        "buffer-row-bg": "#1e293b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "lg": "24px",
        "xs": "4px",
        "margin-mobile": "16px",
        "md": "16px",
        "container-max": "1280px",
        "xl": "48px",
        "base": "4px",
        "2xl": "3rem",
        "sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "label-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "sans": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
